## 1. 판다스(Pandas)

In [28]:
import pandas as pd

In [7]:
sr = pd.Series([17000, 18000, 1000, 5000],
       index=["피자", "치킨", "콜라", "맥주"])
print(sr)
print(sr.values)
print(sr.index)

피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64
[17000 18000  1000  5000]
Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


In [8]:
values = [[1,2,3], [4,5,6], [7,8,9]]
index = ['one', 'two', 'three']
columns = ['a', 'b', 'c']

df = pd.DataFrame(values, index=index, columns=columns)
print(df)

       a  b  c
one    1  2  3
two    4  5  6
three  7  8  9


In [9]:
print(df.index)

Index(['one', 'two', 'three'], dtype='object')


In [10]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(df.columns)

Index(['a', 'b', 'c'], dtype='object')


In [12]:
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [13]:
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [14]:
data = { '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data)
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


## 2. Numpy

In [2]:
import numpy as np
np.__version__

'1.16.5'

### 1) np.array()

In [9]:
a = np.array([1,2,3,4,5])
print(type(a))
b = np.array([[10, 20, 30], [ 60, 70, 80]])
print(b.shape)
print(b.ndim)
print(a.ndim)

<class 'numpy.ndarray'>
(2, 3)
2
1


### 2) ndarray의 초기화

In [12]:
# 모든 배열내의 값 0
a = np.zeros((2,3))
print(a)
# 모든 배열내의 값1
a = np.ones((2,3))
print(a)
# 임의의 값
a = np.random.random((2,5))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.68451851 0.09568247 0.24043344 0.97365263 0.00626043]
 [0.95478366 0.71465271 0.80465197 0.16413217 0.80250232]]


In [17]:
# 특정값으로 배열 채우기
a = np.full((2,3), 8)
print(a)
# 대각선 1 : 5 X 5
a = np.eye(5)
print(a)

[[8 8 8]
 [8 8 8]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3) np.arange()

In [21]:
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### 4) reshape()

In [23]:
a = np.array(np.arange(30)).reshape((5, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5) Numpy 슬라이싱

In [27]:
a = np.array([[1,2,3,], [4,5,6]])
b = a[0:2, 0:2]
print(b)

# 첫번째 행 출력
b = a[0, :]
print(b)

# 두번째 열 출력
b = a[:, 1]
print(b)

[[1 2]
 [4 5]]
[1 2 3]
[2 5]


### 6) Numpy 정수 인덱싱

In [29]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
# a[[row2, col1],[row1, col0]을 의미함
b = a[[2,1], [1, 0]]
print(b)

[[1 2]
 [3 4]
 [5 6]]
[6 3]


### 7) Numpy 연산

In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])

b = x + y
# b = np.add(x, y)와 동일함
print(b)

b = x - y
# b = np.substract(x, y)와 동일함
print(b)

b = b * x
# b = np.multiply(b, x)와 동일함
print(b)

b = b / x
# b = np.divide(b, x)와 동일함
print(b)

[5 7 9]
[-3 -3 -3]
[-3 -6 -9]
[-3. -3. -3.]


In [34]:
# 행렬곱
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
