# 벡터와 행렬 연산

### 텐서(Tensor)

In [1]:
import numpy as np

#### 1) 0차원 텐서

In [3]:
d = np.array(5)
print(d.ndim)
print(d.shape)

0
()


#### 2) 1차원 텐서

In [4]:
d = np.array([1,2,3,4])
print(d.ndim)
print(d.shape)

1
(4,)


#### 3) 2차원 텐서

In [5]:
d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(d.ndim)
print(d.shape)

2
(3, 4)


#### 4) 3차원 텐서

In [6]:
d=np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


### 벡터와 행렬의 연산

#### 1) 벡터와 행렬의 덧셈과 뺄셈

In [7]:
a = np.array([8,4,5])
b = np.array([1,2,3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


#### 2) 벡터의 내적과 행렬의 곱셈

In [9]:
# 벡터 내적
print(np.dot(a,b))

31


In [11]:
# 행렬 곱셈
a = np.array([[1, 3],[2, 4]])
b = np.array([[5, 7],[6, 8]])
print(np.matmul(a,b))

[[23 31]
 [34 46]]
